sudo: required

services:
    - docker

before_install:
    - docker build -t jorens/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jorens/react-test npm test -- --coverage

after_success:
    - docker build -t jorens/multi-client ./client
    - docker build -t jorens/multi-nginx ./nginx
    - docker build -t jorens/multi-server ./server
    - docker build -t jorens/multi-worker ./worker


    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take images and push them to docker hub
    - docker push jorens/multi-client
    - docker push jorens/multi-nginx
    - docker push jorens/multi-server
    - docker push jorens/multi-worker